<?xml version="1.0" ?>

<!DOCTYPE gail [
        <!ELEMENT gail (ui, genie)>
        <!ELEMENT ui (question+, hypothesis+, data+, generalizations+)>
        <!ELEMENT question (#PCDATA)>
        <!ATTLIST question quest CDATA #REQUIRED>
        <!ATTLIST question node_id CDATA #REQUIRED>
        <!ELEMENT hypothesis (#PCDATA)>
        <!ATTLIST hypothesis hypo CDATA #REQUIRED>
        <!ATTLIST hypothesis node_id CDATA #REQUIRED>
        <!ELEMENT data (#PCDATA)>
        <!ATTLIST data datum CDATA #REQUIRED>
        <!ATTLIST data node_id CDATA #REQUIRED>
        <!ELEMENT generalizations (#PCDATA)>
        <!ATTLIST generalizations gen CDATA #REQUIRED>
        <!ATTLIST generalizations node_id CDATA #REQUIRED>
        <!ELEMENT genie (KB_Node, KB_Arc, Argument)>
        <!ELEMENT KB_Node (person+, genotype*, biochemistry*, symptom*, test*, physiology*)>
        <!ELEMENT person (person_name, gender, age, family)>
        <!ELEMENT person_name (#PCDATA)>
        <!ELEMENT gender (#PCDATA)>
        <!ELEMENT age (#PCDATA)>
        <!ELEMENT family (#PCDATA)>
        <!ATTLIST person person_id CDATA #REQUIRED>
        <!ELEMENT biochemistry (protein_id, protein_name, bioAbnormal, quantity)>
        <!ATTLIST biochemistry node_id CDATA #REQUIRED>
        <!ATTLIST biochemistry person_id CDATA #REQUIRED>
        <!ATTLIST biochemistry certainty CDATA #REQUIRED>
        <!ELEMENT protein_id (#PCDATA)>
        <!ELEMENT protein_name (#PCDATA)>
        <!ELEMENT bioAbnormal (#PCDATA)>
        <!ELEMENT quantity (#PCDATA)>
        <!ELEMENT symptom (symptom_id, symptom_name, degree, symAbnormal)>
        <!ATTLIST symptom node_id CDATA #REQUIRED>
        <!ATTLIST symptom person_id CDATA #REQUIRED>
        <!ATTLIST symptom certainty CDATA #REQUIRED>
        <!ELEMENT symptom_id (#PCDATA)>
        <!ELEMENT symptom_name (#PCDATA)>
        <!ELEMENT degree (#PCDATA)>
        <!ELEMENT symAbnormal (#PCDATA)>
        <!ELEMENT genotype (gene_id, gene_name, mutated, autosomal_type, disease, cell)>
        <!ATTLIST genotype node_id CDATA #REQUIRED>
        <!ATTLIST genotype person_id CDATA #REQUIRED>
        <!ATTLIST genotype certainty CDATA #REQUIRED>
        <!ELEMENT person_id (#PCDATA)>
        <!ELEMENT certainty (#PCDATA)>
        <!ELEMENT gene_id (#PCDATA)>
        <!ELEMENT gene_name (#PCDATA)>
        <!ELEMENT mutated (#PCDATA)>
        <!ELEMENT autosomal_type (#PCDATA)>
        <!ELEMENT disease (#PCDATA)>
        <!ELEMENT cell (#PCDATA)>
        <!ATTLIST test node_id CDATA #REQUIRED>
        <!ATTLIST test person_id CDATA #REQUIRED>
        <!ELEMENT test (testName, testAbnormal, testResult)>
        <!ELEMENT testName (#PCDATA)>
        <!ELEMENT testAbnormal (#PCDATA)>
        <!ELEMENT testResult (#PCDATA)>
        <!ATTLIST physiology node_id CDATA #REQUIRED>
        <!ATTLIST physiology person_id CDATA #REQUIRED>
        <!ATTLIST physioligy certaintity CDATA #REQUIRED>
        <!ELEMENT physiology (bodyLocation, description, phyAbnormal)>
        <!ELEMENT bodyLocation (#PCDATA)>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT phyAbnormal (#PCDATA)>
        <!ELEMENT KB_Arc (influence_arc+, synergy_arc_set+)>
        <!ATTLIST synergy_arc_set syn_id CDATA #REQUIRED>
        <!ELEMENT synergy_arc_set (type, child, parent+)>
        <!ELEMENT type (#PCDATA)>
        <!ELEMENT child (#PCDATA)>
        <!ELEMENT parent (#PCDATA)>
        <!ELEMENT influence_arc (influence_type, influence_parent, influence_child)>
        <!ATTLIST influence_arc arc_id CDATA #REQUIRED>
        <!ELEMENT influence_type (#PCDATA)>
        <!ELEMENT influence_parent (#PCDATA)>
        <!ELEMENT influence_child (#PCDATA)>
        <!ELEMENT Argument (argument_id, scheme, argument_data, warrant, conclusion, generalization)>
        <!ELEMENT argument_id (#PCDATA)>
        <!ELEMENT scheme (#PCDATA)>
        <!ELEMENT argument_data (#PCDATA)>
        <!ELEMENT warrant (#PCDATA)>
        <!ELEMENT conclusion (#PCDATA)>
        <!ELEMENT generalization (generalization_path)>
        <!ELEMENT generalization_path (#PCDATA)>
        ]>

<gail>
    <ui>
        <!--node_id 100 is false information and node_id 200 is unknown-->
        <question quest="q1" node_id="7">Give 2 arguments for the hypothesis that J.B. has cystic fibrosis (has 2 mutated copies of the CFTR gene).</question>
        <question quest="q2" node_id="3">Give one argument for the hypothesis that J.B.'s mother has 1 or 2 mutated copies of the CFTR gene.</question>
        <question quest="q3" node_id="2">Give one argument for the hypothesis that the mother does not have 2 mutated copies of the CFTR gene.</question>
        <question quest="q4" node_id="1">Give one argument for the hypothesis that J.B.'s mother has 1 normal and 1 mutated copy of the CFTR gene.</question>
        <hypothesis hypo="h1" node_id ="7">J. B. has cystic fibrosis (has 2 mutated copies of the CFTR gene).</hypothesis>
        <hypothesis hypo="h2" node_id ="100">J.B.'s mother does not have any CFTR gene mutations (both copies of the CFTR gene are normal).</hypothesis>
        <hypothesis hypo="h3" node_id ="3">J.B.'s mother has 1 or 2 mutated copies of the CFTR gene.</hypothesis>
        <hypothesis hypo="h4" node_id="1">J.B.'s mother is a carrier of the CFTR gene mutation (has 1 normal copy and 1 mutated copy of the CFTR gene).</hypothesis>
        <hypothesis hypo="h5" node_id="2">J.B.'s mother does not have 2 mutated copies of the CFTR gene.</hypothesis>
        <hypothesis hypo="h6" node_id="100">J. B.'s mother has cystic fibrosis (has 2 mutated copies of the CFTR gene).</hypothesis>
        <hypothesis hypo="h7" node_id="100">J.B.'s father does not have any CFTR gene mutations (both copies of the CFTR gene are normal).</hypothesis>
        <hypothesis hypo="h8" node_id="4">J.B.'s father is a carrier of the CFTR gene mutation (has one normal copy and one mutated copy of the CFTR gene).</hypothesis>
        <hypothesis hypo="h9" node_id="100">J. B.'s father has cystic fibrosis (has two mutated copies of the CFTR gene in all of his cells).</hypothesis>
        <!--new HYPO-->
        <hypothesis hypo="h10" node_id="9">J.B's CFTR protein is abnormal</hypothesis>
        <hypothesis hypo="h11" node_id="15">J.B. has thick mucus secretion from her lungs.</hypothesis>
        <hypothesis hypo="h12" node_id="17">J.B's mother's CFTR protein is not abnormal</hypothesis>
        <hypothesis hypo="h13" node_id="18">J.B.'s mother has normal mucus secretion from her lungs.</hypothesis>
        <hypothesis hypo="h14" node_id="19">J.B's father's CFTR protein is not abnormal</hypothesis>
        <hypothesis hypo="h15" node_id="20">J.B.'s father has normal mucus secretion from his lungs.</hypothesis>
        <data datum="d1" node_id ="200">Patient: J.B., a 2-year old girl.</data>
        <data datum="d2" node_id= "10">History of respiratory problems: During her second year, J.B. developed a chronic cough and has had frequent upper respiratory infections.</data>
        <data datum="d3" node_id="12">J.B.'s mother does not have a history of respiratory problems.</data>
        <data datum="d4" node_id="11">J.B.'s father does not have a history of respiratory problems.</data>
        <data datum="d5" node_id="14">Test result: J.B.'s chloride level is 75 mmol/L.</data>
        <data datum="d6" node_id="8">J.B.'s 5-year old brother B.B. was diagnosed as having cystic fibrosis.</data>
        <data datum="d7" node_id="13">J.B.'s pancreas is functioning normally.</data>
        <!--Use commas to delimit multiple arc IDs-->
        <generalizations gen="g1" node_id="I1, I5, I6, I11, I12">Cystic fibrosis is the name of a disease caused by having two mutated copies of the CFTR gene. When both copies of CFTR are mutated, the body produces abnormal CFTR protein.</generalizations>
        <generalizations gen="g2" node_id="I3, I15, I17">People with CFTR protein often have viscous secretions in the lungs.</generalizations>
        <generalizations gen="g3" node_id="I4, I16, I18">Viscous secretion provides a medium for growth of bacteria, and which may result in frequent respiratory infections.</generalizations>
        <generalizations gen="g4" node_id="I13">Dysfunction of CFTR may affect the pancreas.</generalizations>
        <generalizations gen="g5" node_id="I14">Pancreatic abnormality may result in malnutrition and poor growth.</generalizations>
        <generalizations gen="g6" node_id="S1, S2">Cystic fibrosis is inherited in an autosomal recessive manner, which means that an individual with cystic fibrosis inherited two mutated copies of the CFTR gene: one from the mother and one from the father.</generalizations>
        <generalizations gen="g7" node_id="200">If one parent is a carrier (has one copy of the mutation) and the other parent has no copies of the mutation, each offspring has a 25 percent chance of being a carrier.</generalizations>
        <generalizations gen="g8" node_id="200">Although cystic fibrosis classically manifests in early childhood, approximately 4 percent of patients are diagnosed in adulthood.</generalizations>
        <generalizations gen="g9" node_id="I2">In the absence of normal CFTR protein, sweat has an increased sodium chloride content. Most patients with cystic fibrosis show an elevated level of sweat chloride (more than 60 mmol/L).</generalizations>
    </ui>
    <genie>
        <KB_Node>
            <person person_id="1">
                <person_name>Mother</person_name>
                <gender>F</gender>
                <age>32</age>
                <family> </family>
            </person>
            <person person_id="2">
                <person_name>Father</person_name>
                <gender>M</gender>
                <age>33</age>
                <family> </family>
            </person>
            <person person_id="3">
                <person_name>JB</person_name>
                <gender>F</gender>
                <age>2</age>
                <family>1 2</family>
            </person>
            <person person_id="4">
                <person_name>Brother</person_name>
                <gender>M</gender>
                <age>3</age>
                <family>1 2</family>
            </person>
            <!-- Mother nodes -->
            <genotype node_id="1" person_id="1" certainty="">
                <gene_id>FLAG</gene_id>
                <gene_name>CFTR</gene_name>
                <mutated>1</mutated>
                <autosomal_type>recessive</autosomal_type>
                <disease>Cystic Fibrosis</disease>
                <cell>FLAG</cell>
            </genotype>
            <genotype node_id="2" person_id="1" certainty="">
                <gene_id>FLAG</gene_id>
                <gene_name>CFTR</gene_name>
                <mutated>0...1</mutated>
                <autosomal_type>recessive</autosomal_type>
                <disease>Cystic Fibrosis</disease>
                <cell>FLAG</cell>
            </genotype>
            <genotype node_id="3" person_id="1" certainty="">
                <gene_id>FLAG</gene_id>
                <gene_name>CFTR</gene_name>
                <mutated>1...2</mutated>
                <autosomal_type>recessive</autosomal_type>
                <disease>Cystic Fibrosis</disease>
                <cell>FLAG</cell>
            </genotype>
            <biochemistry node_id="17" person_id="1" certainty="">
                <protein_id>FLAG</protein_id>
                <protein_name>CFTR</protein_name>
                <bioAbnormal>false</bioAbnormal>
                <quantity>normal</quantity>
            </biochemistry>
            <physiology node_id="18" person_id="1">
                <bodyLocation>lung secretion</bodyLocation>
                <description>thickened mucus</description>
                <phyAbnormal>false</phyAbnormal>
            </physiology>
            <!-- Father nodes -->
            <genotype node_id="4" person_id="2" certainty="">
                <gene_id>FLAG</gene_id>
                <gene_name>CFTR</gene_name>
                <mutated>1</mutated>
                <autosomal_type>recessive</autosomal_type>
                <disease>Cystic Fibrosis</disease>
                <cell>FLAG</cell>
            </genotype>
            <genotype node_id="5" person_id="2" certainty="">
                <gene_id>FLAG</gene_id>
                <gene_name>CFTR</gene_name>
                <mutated>1...2</mutated>
                <autosomal_type>recessive</autosomal_type>
                <disease>Cystic Fibrosis</disease>
                <cell>FLAG</cell>
            </genotype>
            <genotype node_id="6" person_id="2" certainty="">
                <gene_id>FLAG</gene_id>
                <gene_name>CFTR</gene_name>
                <mutated>0...1</mutated>
                <autosomal_type>recessive</autosomal_type>
                <disease>Cystic Fibrosis</disease>
                <cell>FLAG</cell>
            </genotype>
            <biochemistry node_id="19" person_id="2" certainty="">
                <protein_id>FLAG</protein_id>
                <protein_name>CFTR</protein_name>
                <bioAbnormal>false</bioAbnormal>
                <quantity>normal</quantity>
            </biochemistry>
            <physiology node_id="20" person_id="2">
                <bodyLocation>lung secretion</bodyLocation>
                <description>thickened mucus</description>
                <phyAbnormal>false</phyAbnormal>
            </physiology>
            <!-- Brother Node-->
            <genotype node_id="8" person_id="4" certainty="">
                <gene_id>FLAG</gene_id>
                <gene_name>CFTR</gene_name>
                <mutated>2</mutated>
                <autosomal_type>recessive</autosomal_type>
                <disease>Cystic Fibrosis</disease>
                <cell>FLAG</cell>
            </genotype>
            <!-- J.B. Node -->
            <genotype node_id="7" person_id="3" certainty="">
                <gene_id>FLAG</gene_id>
                <gene_name>CFTR</gene_name>
                <mutated>2</mutated>
                <autosomal_type>recessive</autosomal_type>
                <disease>Cystic Fibrosis</disease>
                <cell>FLAG</cell>
            </genotype>
            <biochemistry node_id="9" person_id="3" certainty="">
                <protein_id>FLAG</protein_id>
                <protein_name>CFTR</protein_name>
                <bioAbnormal>true</bioAbnormal>
                <quantity>normal</quantity>
            </biochemistry>
             <symptom node_id="10" person_id="3" certainty="">
                <symptom_id>FLAG</symptom_id>
                <symptom_name>Frequent cough and upper respiratory infections</symptom_name>
                <degree>severe</degree>
                 <symAbnormal>true</symAbnormal>
            </symptom>
            <symptom node_id="11" person_id="2" certainty="">
                <symptom_id>FLAG</symptom_id>
                <symptom_name>Upper respiratory infections</symptom_name>
                <degree>absent</degree>
                <symAbnormal>false</symAbnormal>
            </symptom>
            <symptom node_id="12" person_id="1" certainty="">
                <symptom_id>FLAG</symptom_id>
                <symptom_name>Upper respiratory infections</symptom_name>
                <degree>absent</degree>
                <symAbnormal>false</symAbnormal>
            </symptom>
            <symptom node_id="13" person_id="3" certainty="">
                <symptom_id>FLAG</symptom_id>
                <symptom_name>Malnutrition and poor growth</symptom_name>
                <degree>absent</degree>
                <symAbnormal>false</symAbnormal>
            </symptom>
            <test node_id = "14" person_id="3">
                <testName>Sweat Chloride Test</testName>
                <testAbnormal>true</testAbnormal>
                <testResult>75 mmol/L.</testResult>
            </test>
            <physiology node_id="15" person_id="3">
                <bodyLocation>Lung secretions</bodyLocation>
                <description>Thickened Mucus</description>
                <phyAbnormal>true</phyAbnormal>
            </physiology>
            <physiology node_id="16" person_id="3">
                <bodyLocation>Pancreas Abnormal</bodyLocation>
                <description>absent</description>
                <phyAbnormal>false</phyAbnormal>
            </physiology>
        </KB_Node>
        <KB_Arc>
            <influence_arc arc_id="I1">
                <influence_type>+</influence_type>
                <influence_parent>7</influence_parent>
                <influence_child>9</influence_child>
            </influence_arc>
            <influence_arc arc_id="I2">
                <influence_type>+</influence_type>
                <influence_parent>9</influence_parent>
                <influence_child>14</influence_child>
            </influence_arc>
            <influence_arc arc_id="I3">
                <influence_type>+</influence_type>
                <influence_parent>9</influence_parent>
                <influence_child>15</influence_child>
            </influence_arc>
            <influence_arc arc_id="I4">
                <influence_type>+</influence_type>
                <influence_parent>15</influence_parent>
                <influence_child>10</influence_child>
            </influence_arc>
            <influence_arc arc_id="I5">
                <influence_type>+</influence_type>
                <influence_parent>4</influence_parent>
                <influence_child>19</influence_child>
            </influence_arc>
            <influence_arc arc_id="I6">
                <influence_type>+</influence_type>
                <influence_parent>1</influence_parent>
                <influence_child>17</influence_child>
            </influence_arc>
            <influence_arc arc_id="%1">
                <influence_type>%</influence_type>
                <influence_parent>1</influence_parent>
                <influence_child>2</influence_child>
            </influence_arc>
            <influence_arc arc_id="%2">
                <influence_type>%</influence_type>
                <influence_parent>1</influence_parent>
                <influence_child>3</influence_child>
            </influence_arc>
            <influence_arc arc_id="%3">
                <influence_type>%</influence_type>
                <influence_parent>4</influence_parent>
                <influence_child>5</influence_child>
            </influence_arc>
            <influence_arc arc_id="%4">
                <influence_type>%</influence_type>
                <influence_parent>4</influence_parent>
                <influence_child>6</influence_child>
            </influence_arc>
            <influence_arc arc_id="I11">
                <influence_type>+</influence_type>
                <influence_parent>2</influence_parent>
                <influence_child>17</influence_child>
            </influence_arc>
            <influence_arc arc_id="I12">
                <influence_type>+</influence_type>
                <influence_parent>6</influence_parent>
                <influence_child>19</influence_child>
            </influence_arc>
            <influence_arc arc_id="I13">
                <influence_type>+</influence_type>
                <influence_parent>9</influence_parent>
                <influence_child>16</influence_child>
            </influence_arc>
            <influence_arc arc_id="I14">
                <influence_type>+</influence_type>
                <influence_parent>16</influence_parent>
                <influence_child>13</influence_child>
            </influence_arc>
            <!--NEW Nodes added-->
            <influence_arc arc_id="I15">
                <influence_type>+</influence_type>
                <influence_parent>17</influence_parent>
                <influence_child>18</influence_child>
            </influence_arc>
            <influence_arc arc_id="I16">
                <influence_type>+</influence_type>
                <influence_parent>18</influence_parent>
                <influence_child>12</influence_child>
            </influence_arc>
            <influence_arc arc_id="I17">
                <influence_type>+</influence_type>
                <influence_parent>19</influence_parent>
                <influence_child>20</influence_child>
            </influence_arc>
            <influence_arc arc_id="I18">
                <influence_type>+</influence_type>
                <influence_parent>20</influence_parent>
                <influence_child>11</influence_child>
            </influence_arc>

            <synergy_arc_set syn_id="S1">
                <type>X0</type>
                <child>7</child>
                <parent>3</parent>
                <parent>5</parent>
            </synergy_arc_set>
            <synergy_arc_set syn_id="S2">
                <type>X0</type>
                <child>8</child>
                <parent>3</parent>
                <parent>5</parent>
            </synergy_arc_set>
        </KB_Arc>
        <Argument>
            <argument_id></argument_id>
            <scheme></scheme>
            <argument_data></argument_data>
            <warrant></warrant>
            <conclusion></conclusion>
            <generalization>
                <generalization_path></generalization_path>
            </generalization>
        </Argument>
    </genie>
</gail>