<?xml version="1.0" ?>

<!DOCTYPE gail [
        <!ELEMENT gail (ui, genie)>
        <!ELEMENT ui (question+, hypothesis+, data+, generalizations+)>
        <!ELEMENT question (#PCDATA)>
        <!ATTLIST question quest CDATA #REQUIRED>
        <!ATTLIST question node_id CDATA #REQUIRED>
        <!ELEMENT hypothesis (#PCDATA)>
        <!ATTLIST hypothesis hypo CDATA #REQUIRED>
        <!ATTLIST hypothesis node_id CDATA #REQUIRED>
        <!ELEMENT data (#PCDATA)>
        <!ATTLIST data datum CDATA #REQUIRED>
        <!ATTLIST data node_id CDATA #REQUIRED>
        <!ELEMENT generalizations (#PCDATA)>
        <!ATTLIST generalizations gen CDATA #REQUIRED>
        <!ATTLIST generalizations node_id CDATA #REQUIRED>
        <!ELEMENT genie (KB_Node, KB_Arc, Argument)>
        <!ELEMENT KB_Node (person+, genotype*, biochemistry*, symptom*, test*, physiology*)>
        <!ELEMENT person (person_name, gender, age, family)>
        <!ELEMENT person_name (#PCDATA)>
        <!ELEMENT gender (#PCDATA)>
        <!ELEMENT age (#PCDATA)>
        <!ELEMENT family (#PCDATA)>
        <!ATTLIST person person_id CDATA #REQUIRED>
        <!ELEMENT biochemistry (protein_id, protein_name, bioAbnormal, quantity)>
        <!ATTLIST biochemistry node_id CDATA #REQUIRED>
        <!ATTLIST biochemistry person_id CDATA #REQUIRED>
        <!ATTLIST biochemistry certainty CDATA #REQUIRED>
        <!ELEMENT protein_id (#PCDATA)>
        <!ELEMENT protein_name (#PCDATA)>
        <!ELEMENT bioAbnormal (#PCDATA)>
        <!ELEMENT quantity (#PCDATA)>
        <!ELEMENT symptom (symptom_id, symptom_name, degree, symAbnormal)>
        <!ATTLIST symptom node_id CDATA #REQUIRED>
        <!ATTLIST symptom person_id CDATA #REQUIRED>
        <!ATTLIST symptom certainty CDATA #REQUIRED>
        <!ELEMENT symptom_id (#PCDATA)>
        <!ELEMENT symptom_name (#PCDATA)>
        <!ELEMENT degree (#PCDATA)>
        <!ELEMENT symAbnormal (#PCDATA)>
        <!ELEMENT genotype (gene_id, gene_name, mutated, autosomal_type, disease, cell)>
        <!ATTLIST genotype node_id CDATA #REQUIRED>
        <!ATTLIST genotype person_id CDATA #REQUIRED>
        <!ATTLIST genotype certainty CDATA #REQUIRED>
        <!ELEMENT person_id (#PCDATA)>
        <!ELEMENT certainty (#PCDATA)>
        <!ELEMENT gene_id (#PCDATA)>
        <!ELEMENT gene_name (#PCDATA)>
        <!ELEMENT mutated (#PCDATA)>
        <!ELEMENT autosomal_type (#PCDATA)>
        <!ELEMENT disease (#PCDATA)>
        <!ELEMENT cell (#PCDATA)>
        <!ATTLIST test node_id CDATA #REQUIRED>
        <!ATTLIST test person_id CDATA #REQUIRED>
        <!ELEMENT test (testName, testAbnormal, testResult)>
        <!ELEMENT testName (#PCDATA)>
        <!ELEMENT testAbnormal (#PCDATA)>
        <!ELEMENT testResult (#PCDATA)>
        <!ATTLIST physiology node_id CDATA #REQUIRED>
        <!ATTLIST physiology person_id CDATA #REQUIRED>
        <!ATTLIST physioligy certaintity CDATA #REQUIRED>
        <!ELEMENT physiology (bodyLocation, description, phyAbnormal)>
        <!ELEMENT bodyLocation (#PCDATA)>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT phyAbnormal (#PCDATA)>
        <!ELEMENT KB_Arc (influence_arc+, synergy_arc_set+)>
        <!ATTLIST synergy_arc_set syn_id CDATA #REQUIRED>
        <!ELEMENT synergy_arc_set (type, child, parent+)>
        <!ELEMENT type (#PCDATA)>
        <!ELEMENT child (#PCDATA)>
        <!ELEMENT parent (#PCDATA)>
        <!ELEMENT influence_arc (influence_type, influence_parent, influence_child)>
        <!ATTLIST influence_arc arc_id CDATA #REQUIRED>
        <!ELEMENT influence_type (#PCDATA)>
        <!ELEMENT influence_parent (#PCDATA)>
        <!ELEMENT influence_child (#PCDATA)>
        <!ELEMENT Argument (argument_id, scheme, argument_data, warrant, conclusion, generalization)>
        <!ELEMENT argument_id (#PCDATA)>
        <!ELEMENT scheme (#PCDATA)>
        <!ELEMENT argument_data (#PCDATA)>
        <!ELEMENT warrant (#PCDATA)>
        <!ELEMENT conclusion (#PCDATA)>
        <!ELEMENT generalization (generalization_path)>
        <!ELEMENT generalization_path (#PCDATA)>
        ]>
<gail>
    <ui>
        <question quest="q1" node_id="1">Give one argument for hypothesis that PP does not have HNPCC.</question>
        <question quest="q2" node_id="6">Give one argument for hypothesis that PP will not develop colon cancer.
        </question>
        <question quest="q3" node_id="3">Give one argument for hypothesis that PP's child does not have HNPCC.</question>
        <question quest="q4" node_id="4">Give one argument for hypothesis that PP's father had HNPCC.</question>
        <question quest="q5" node_id="5">Give one argument for hypothesis that PP's mother does not have HNPCC.
        </question>
        <!--node_id 100 is false information and node_id 200 is unknown-->
        <hypothesis hypo="h1" node_id="100">PP has HNPCC.</hypothesis>
        <hypothesis hypo="h2" node_id="1">PP does not have HNPCC (has no mutation of MLH1).</hypothesis>
        <hypothesis hypo="h3" node_id="2">PP's brother has HNPCC (one mutation of MLH1).</hypothesis>
        <hypothesis hypo="h4" node_id="100">PP's brother does not have HNPCC (has no mutation of MLH1).</hypothesis>
        <hypothesis hypo="h5" node_id="4">PP's father has HNPCC (one mutation of MLH1).</hypothesis>
        <hypothesis hypo="h6" node_id="100">PP's father does not have HNPCC (has no mutation of MLH1).</hypothesis>
        <hypothesis hypo="h7" node_id="100">PP will develop colon cancer.</hypothesis>
        <hypothesis hypo="h8" node_id="100">PP will not develop colon cancer.</hypothesis>
        <hypothesis hypo="h9" node_id="100">PP's child has HNPCC (one mutation of MLH1).</hypothesis>
        <hypothesis hypo="h10" node_id="3">PP's child does not have HNPCC (has no mutation of MLH1.)</hypothesis>
        <hypothesis hypo="h12" node_id="5">NEW: PP's mother does not have HNPCC</hypothesis>
        <data datum="d1" node_id="6">PP is a 40 year old male that does not have colon cancer.</data>
        <data datum="d2" node_id="9">PP's deceased father had colon cancer.</data>
        <data datum="d3" node_id="10">PP's deceased mother did not have colon cancer.</data>
        <data datum="d4" node_id="7">PP's brother has colon cancer.</data>
        <data datum="d5" node_id="12">PP's brother's test result is positive (one mutation of MLH1).</data>
        <data datum="d6" node_id="11">PP's test result is negative (no mutation of MLH1).</data>
        <data datum="d7" node_id="8">NEW: PP's child may not have HNPCC</data>
        <generalizations gen="g1" node_id="I1, I2, I3, I4, I7">HNPCC is an autosomal dominant condition in which one copy of the MLH1 is
            mutated. Having HNPCC increases the lifetime risk of colon cancer.</generalizations>
        <generalizations gen="g2" node_id="I5, I6">Having one mutated copy of MLH1 gene is indicated by a positive gene test for MLH1 mutations</generalizations>
        <generalizations gen="g3" node_id="S1, S2, S3">A child inherits one copy of a gene from each parent.</generalizations>
    </ui>
    <genie>
        <KB_Node>
            <person person_id="1">
                <person_name>PP</person_name>
                <gender>M</gender>
                <age>40</age>
                <family> </family>
            </person>
            <person person_id="2">
                <person_name>PP_brother</person_name>
                <gender>M</gender>
                <age>55</age>
                <family> </family>
            </person>
            <person person_id="3">
                <person_name>PP_child</person_name>
                <gender>M</gender>
                <age>12</age>
                <family> </family>
            </person>
            <person person_id="4">
                <person_name>PP_father</person_name>
                <gender>M</gender>
                <age>80</age>
                <family> </family>
            </person>
            <person person_id="5">
                <person_name>PP_mother</person_name>
                <gender>M</gender>
                <age>79</age>
                <family> </family>
            </person>
            <person person_id="6">
                <person_name>PP_wife</person_name>
                <gender>F</gender>
                <age>37</age>
                <family> </family>
            </person>
            <genotype node_id="1" person_id="1" certainty="">
                <gene_id>FLAG</gene_id>
                <gene_name>MLH1</gene_name>
                <mutated>0</mutated>
                <autosomal_type>dominant</autosomal_type>
                <disease>Hereditary Colon Cancer</disease>
                <cell>FLAG</cell>
            </genotype>
            <genotype node_id="2" person_id="2" certainty="">
                <gene_id>FLAG</gene_id>
                <gene_name>MLH1</gene_name>
                <mutated>1</mutated>
                <autosomal_type>dominant</autosomal_type>
                <disease>Hereditary Colon Cancer</disease>
                <cell>FLAG</cell>
            </genotype>
            <genotype node_id="3" person_id="3" certainty="">
                <gene_id>FLAG</gene_id>
                <gene_name>MLH1</gene_name>
                <mutated>0...1</mutated>
                <autosomal_type>dominant</autosomal_type>
                <disease>Hereditary Colon Cancer</disease>
                <cell>FLAG</cell>
            </genotype>
            <genotype node_id="4" person_id="4" certainty="">
                <gene_id>FLAG</gene_id>
                <gene_name>MLH1</gene_name>
                <mutated>1</mutated>
                <autosomal_type>dominant</autosomal_type>
                <disease>Hereditary Colon Cancer</disease>
                <cell>FLAG</cell>
            </genotype>
            <genotype node_id="5" person_id="5" certainty="">
                <gene_id>FLAG</gene_id>
                <gene_name>MLH1</gene_name>
                <mutated>0</mutated>
                <autosomal_type>dominant</autosomal_type>
                <disease>Hereditary Colon Cancer</disease>
                <cell>FLAG</cell>
            </genotype>
            <genotype node_id="13" person_id="6" certainty="">
                <gene_id>FLAG</gene_id>
                <gene_name>MLH1</gene_name>
                <mutated>0</mutated>
                <autosomal_type>dominant</autosomal_type>
                <disease>Hereditary Colon Cancer</disease>
                <cell>FLAG</cell>
            </genotype>
            <symptom node_id="6" person_id="1" certainty="">
                <symptom_id>FLAG</symptom_id>
                <symptom_name>Colon Cancer</symptom_name>
                <degree>absent</degree>
                <symAbnormal>false</symAbnormal>
            </symptom>
            <symptom node_id="7" person_id="2" certainty="">
                <symptom_id>FLAG</symptom_id>
                <symptom_name>Colon Cancer</symptom_name>
                <degree>severe</degree>
                <symAbnormal>true</symAbnormal>
            </symptom>
            <symptom node_id="8" person_id="3" certainty="">
                <symptom_id>FLAG</symptom_id>
                <symptom_name>Colon Cancer</symptom_name>
                <degree>absent</degree>
                <symAbnormal>possible</symAbnormal>
            </symptom>
            <symptom node_id="9" person_id="4" certainty="">
                <symptom_id>FLAG</symptom_id>
                <symptom_name>Colon Cancer</symptom_name>
                <degree>severe</degree>
                <symAbnormal>true</symAbnormal>
            </symptom>
         <symptom node_id="10" person_id="5" certainty="">
             <symptom_id>FLAG</symptom_id>
             <symptom_name>Colon Cancer</symptom_name>
             <degree>absent</degree>
             <symAbnormal>false</symAbnormal>
         </symptom>
            <test node_id="11" person_id="1">
                <testName>FLAG</testName>
                <testAbnormal>false</testAbnormal>
                <testResult>negative</testResult>
            </test>
            <test node_id="12" person_id="2">
                <testName>FLAG</testName>
                <testAbnormal>true</testAbnormal>
                <testResult>positive</testResult>
            </test>
        </KB_Node>
        <KB_Arc>
            <influence_arc arc_id="I1">
                <influence_type>+</influence_type>
                <influence_parent>4</influence_parent>
                <influence_child>9</influence_child>
            </influence_arc>
            <influence_arc arc_id="I2">
                <influence_type>+</influence_type>
                <influence_parent>5</influence_parent>
                <influence_child>10</influence_child>
            </influence_arc>
            <influence_arc arc_id="I3">
                <influence_type>+</influence_type>
                <influence_parent>1</influence_parent>
                <influence_child>6</influence_child>
            </influence_arc>
            <influence_arc arc_id="I4">
                <influence_type>+</influence_type>
                <influence_parent>2</influence_parent>
                <influence_child>7</influence_child>
            </influence_arc>
            <influence_arc arc_id="I5">
                <influence_type>+</influence_type>
                <influence_parent>1</influence_parent>
                <influence_child>11</influence_child>
            </influence_arc>
            <influence_arc arc_id="I6">
                <influence_type>+</influence_type>
                <influence_parent>2</influence_parent>
                <influence_child>12</influence_child>
            </influence_arc>
            <influence_arc arc_id="I7">
                <influence_type>+</influence_type>
                <influence_parent>3</influence_parent>
                <influence_child>8</influence_child>
            </influence_arc>
            <synergy_arc_set syn_id="S1">
                <type>X-</type>
                <child>1</child>
                <parent>4</parent>
                <parent>5</parent>
            </synergy_arc_set>
            <synergy_arc_set syn_id="S2">
                <type>X-</type>
                <child>2</child>
                <parent>4</parent>
                <parent>5</parent>
            </synergy_arc_set>
            <synergy_arc_set syn_id="S3">
                <type>X-</type>
                <child>3</child>
                <parent>1</parent>
            </synergy_arc_set>
        </KB_Arc>
        <Argument>
            <argument_id></argument_id>
            <scheme></scheme>
            <argument_data></argument_data>
            <warrant></warrant>
            <conclusion></conclusion>
            <generalization>
                <generalization_path></generalization_path>
            </generalization>
        </Argument>
    </genie>
</gail>
